package luis.delgado.clubmontana.backend.domain.model.enums;

public enum MailType {
  USER_CREATED,
  USER_REACTIVATED,
  PASSWORD_RESET,
  TEST,
  CONTACT_REQUEST,
  MEMBERSHIP_SIGNUP,
  FEDERATION,
  ACTIVITY_FEDERATE_CLUB,
  ACTIVITY_FEDERATE_NO_CLUB,
  ACTIVITY_NO_FEDERATE_CLUB,
  ACTIVITY_NO_FEDERATE_NO_CLUB;
}
